SHELL:=/bin/bash

#---------------------------------

LOGGER=./log.sh
LOG_INFO=$(LOGGER) INFO

#---------------------------------

data_stem = $(if $(filter %.table, $1),$(basename $(notdir $1)),$(notdir $1))

#------------ create directories -----------

RUN_DIR=tte.run_dir

include makefile.config

$(RUN_DIR) :
	mkdir $@

